### ISSUE TITLE
GitlabCI Retry Build stopped working after 5.2 upgrade

### ISSUE THREAD

**Issue by globexdesigns** [gitlabhq/gitlab-ci#507] opened 2014-12-01 16:24 UTC
When starting a build, Gitlab CI seems to identify and assign my runner, but nothing is ever printed to the console and the build is stuck forever in the "Running" state.

Running GitlabCI 5.2 and Gitlab-CI-Runner 5.0.0.

Which logs should I be looking at?

**Comment by vsizov** [comment] 2015-01-13 04:25
Yeap we will fix it soon. Duplicate of #516

**Closed** 2015-01-13 04:25 UTC
