### ISSUE TITLE
Trying to access the Gitlab CI page results in a 500 error

### ISSUE THREAD

**Issue by Mattsface** [gitlabhq/gitlab-ci#642] opened 2016-03-26 09:41 UTC
I've currently upgrade to the Gitlab ominubus package 8.6.0, and now when I try to access the Gitlab CI page, gitlab.corp.company.com/ci/ it returns a 500 error

This is the trace back I'm seeing in the rails logs
`Processing by Ci::ProjectsController#index as HTML 
Completed 500 Internal Server Error in 85ms (ActiveRecord: 4.1ms)

NoMethodError (undefined method `authorize_read_project!' for #<Ci::ProjectsController:0x000000123d02e0>): 
lib/gitlab/middleware/go.rb:16:in `call' 
lib/gitlab/middleware/readonly_geo.rb:29:in `call'`

I'm running the EE version.

**Comment by Mattsface** [comment] 2016-03-26 09:42
I'm sorry, the code is not pasting well

**Comment by stanhu** [comment] 2016-03-26 13:25
I believe this is a [duplicate of this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/14528) and [fixed here](https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/296) in 8.6.1.

**Closed by stanhu** 2016-03-26 13:25 UTC

**Comment by grzesiek** [comment] 2016-03-27 13:44
This has been indeed fixed, but in this MR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3377, but this is not merged yet.
